<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * shiporder_itemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class shiporder_itemRepository extends EntityRepository
{
}
